# Generated by Django 2.1.7 on 2019-03-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='district',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='second_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='subcounty',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='telephone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='officer',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
