# Generated by Django 2.1.7 on 2019-03-27 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farm', '0002_auto_20190327_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='community_status',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='crop_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='district',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='farm_area',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='instructor_possibility',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='language',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='marriage_status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='parish',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='past_harvest',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='photo',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='farmer',
            name='subcounty',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='telephone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='village',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='registered',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='officer',
            name='district',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='officer',
            name='subcounty',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='officer',
            name='telephone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
