# Generated by Django 2.1.7 on 2019-03-27 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farm', '0003_auto_20190327_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, null=True)),
                ('season', models.CharField(max_length=30, null=True)),
                ('area', models.CharField(max_length=30, null=True)),
                ('rice_type', models.CharField(max_length=30, null=True)),
                ('sowing_date', models.DateTimeField(null=True)),
                ('sowing_type', models.CharField(max_length=10, null=True)),
                ('planting_type', models.CharField(max_length=20, null=True)),
                ('levelling', models.CharField(max_length=20, null=True)),
                ('ridge', models.CharField(max_length=10, null=True)),
                ('whatercourse_state', models.CharField(max_length=15, null=True)),
                ('fertilizer', models.BooleanField(null=True)),
                ('fertilizre1_type', models.CharField(max_length=20, null=True)),
                ('fertilizer1_amount', models.IntegerField(null=True)),
                ('fertilizre2_type', models.CharField(max_length=20, null=True)),
                ('fertilizer2_amount', models.IntegerField(null=True)),
                ('weed_condition', models.CharField(max_length=50, null=True)),
                ('total_weed_times', models.IntegerField(null=True)),
                ('harvest_date', models.DateTimeField(null=True)),
                ('harvest_amount', models.IntegerField(null=True)),
                ('note', models.TextField(null=True)),
                ('photo1', models.FileField(null=True, upload_to='')),
                ('photo2', models.FileField(null=True, upload_to='')),
                ('photo3', models.FileField(null=True, upload_to='')),
                ('photo4', models.FileField(null=True, upload_to='')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='officer',
            old_name='registered',
            new_name='user',
        ),
    ]
