# Generated by Django 2.1.7 on 2019-03-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0005_season'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='officer',
            name='second_name',
        ),
        migrations.AddField(
            model_name='officer',
            name='login_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
