# Generated by Django 2.1.7 on 2019-04-01 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0006_auto_20190328_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('district', models.CharField(max_length=50, null=True)),
                ('parish', models.CharField(max_length=50, null=True)),
                ('sub_county', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='officer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='report',
            name='user',
        ),
        migrations.RemoveField(
            model_name='season',
            name='user',
        ),
        migrations.AddField(
            model_name='farmer',
            name='officers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farm.Officer'),
        ),
        migrations.AddField(
            model_name='report',
            name='farmer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farm.Farmer'),
        ),
        migrations.AddField(
            model_name='season',
            name='farmers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farm.Farmer'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='officer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='season',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='location',
            name='farmer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farm.Farmer'),
        ),
    ]
