# Generated by Django 2.1.7 on 2019-04-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0007_auto_20190401_1906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ('district',)},
        ),
        migrations.RemoveField(
            model_name='location',
            name='farmer',
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
