# Generated by Django 2.1.7 on 2019-04-03 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0009_auto_20190402_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='farmer',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
