# Generated by Django 2.1.5 on 2019-04-05 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0010_auto_20190403_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subcounty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farm.District')),
            ],
        ),
        migrations.RenameField(
            model_name='report',
            old_name='fertilizre1_type',
            new_name='fertilizer1_type',
        ),
        migrations.AlterField(
            model_name='farmer',
            name='instructor_possibility',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='fertilizer',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='parish',
            name='sub_county',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farm.Subcounty'),
        ),
    ]
